postgres:
  ports:
    - '3306:3306'
  restart: always
  image: mysql
  environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  volumes:
    - setup.sql:/docker-entrypoint-initdb.d/setup.sql
